version: '3'
services:
  app:
    build:
      context: ./
    tty: true
    stdin_open: true
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
